#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo usage: $0 language
    exit 0
fi

if [ -e view/$1/messages.po ]; then
    msgmerge view/$1/messages.po util/messages.po
    poedit view/$1/messages.po
    util/po2php view/$1/messages.po
fi
