#!/usr/bin/env bash
if [ ! -d .git ]; then
	echo Unable to update `pwd`
	exit
fi
git pull
# use composer install so that the current composer.lock
# is always used. If this was an update command, it would
# update composer.lock and create an unintentional local file
# modification.
composer install --no-dev
if [ -d extend ] ; then
	for a in  theme addon widget ; do
		if [ -d extend/$a ]; then
			for b in  `ls extend/$a` ; do
				echo Updating $b
				'util/update_'$a'_repo' $b
			done
		fi
	done
fi
